// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma 7: 迁移操作使用直接连接（DIRECT_URL），应用查询使用连接池（DATABASE_URL）
// 迁移时优先使用 DIRECT_URL，如果没有则使用 DATABASE_URL
const MIGRATION_URL = process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || "postgresql://postgres:Fydw%40715@db.qkvgeuallarmbcfjzkko.supabase.co:5432/postgres";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7: 迁移操作使用直接连接（支持 DDL 操作）
    // 应用查询的连接在 PrismaClient 初始化时从环境变量读取
    url: MIGRATION_URL,
  },
});
