
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SourceFolder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SourceFolder
 * 
 */
export type SourceFolderModel = runtime.Types.Result.DefaultSelection<Prisma.$SourceFolderPayload>

export type AggregateSourceFolder = {
  _count: SourceFolderCountAggregateOutputType | null
  _min: SourceFolderMinAggregateOutputType | null
  _max: SourceFolderMaxAggregateOutputType | null
}

export type SourceFolderMinAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  parentId: string | null
  deckId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SourceFolderMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  parentId: string | null
  deckId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SourceFolderCountAggregateOutputType = {
  id: number
  userId: number
  name: number
  parentId: number
  deckId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SourceFolderMinAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  parentId?: true
  deckId?: true
  createdAt?: true
  updatedAt?: true
}

export type SourceFolderMaxAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  parentId?: true
  deckId?: true
  createdAt?: true
  updatedAt?: true
}

export type SourceFolderCountAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  parentId?: true
  deckId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SourceFolderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceFolder to aggregate.
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceFolders to fetch.
   */
  orderBy?: Prisma.SourceFolderOrderByWithRelationInput | Prisma.SourceFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SourceFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SourceFolders
  **/
  _count?: true | SourceFolderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourceFolderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourceFolderMaxAggregateInputType
}

export type GetSourceFolderAggregateType<T extends SourceFolderAggregateArgs> = {
      [P in keyof T & keyof AggregateSourceFolder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSourceFolder[P]>
    : Prisma.GetScalarType<T[P], AggregateSourceFolder[P]>
}




export type SourceFolderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceFolderWhereInput
  orderBy?: Prisma.SourceFolderOrderByWithAggregationInput | Prisma.SourceFolderOrderByWithAggregationInput[]
  by: Prisma.SourceFolderScalarFieldEnum[] | Prisma.SourceFolderScalarFieldEnum
  having?: Prisma.SourceFolderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceFolderCountAggregateInputType | true
  _min?: SourceFolderMinAggregateInputType
  _max?: SourceFolderMaxAggregateInputType
}

export type SourceFolderGroupByOutputType = {
  id: string
  userId: string
  name: string
  parentId: string | null
  deckId: string | null
  createdAt: Date
  updatedAt: Date
  _count: SourceFolderCountAggregateOutputType | null
  _min: SourceFolderMinAggregateOutputType | null
  _max: SourceFolderMaxAggregateOutputType | null
}

type GetSourceFolderGroupByPayload<T extends SourceFolderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourceFolderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourceFolderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceFolderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceFolderGroupByOutputType[P]>
      }
    >
  >



export type SourceFolderWhereInput = {
  AND?: Prisma.SourceFolderWhereInput | Prisma.SourceFolderWhereInput[]
  OR?: Prisma.SourceFolderWhereInput[]
  NOT?: Prisma.SourceFolderWhereInput | Prisma.SourceFolderWhereInput[]
  id?: Prisma.StringFilter<"SourceFolder"> | string
  userId?: Prisma.StringFilter<"SourceFolder"> | string
  name?: Prisma.StringFilter<"SourceFolder"> | string
  parentId?: Prisma.StringNullableFilter<"SourceFolder"> | string | null
  deckId?: Prisma.StringNullableFilter<"SourceFolder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SourceFolder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SourceFolder"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  parent?: Prisma.XOR<Prisma.SourceFolderNullableScalarRelationFilter, Prisma.SourceFolderWhereInput> | null
  children?: Prisma.SourceFolderListRelationFilter
  deck?: Prisma.XOR<Prisma.DeckNullableScalarRelationFilter, Prisma.DeckWhereInput> | null
  sources?: Prisma.SourceListRelationFilter
}

export type SourceFolderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  deckId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  parent?: Prisma.SourceFolderOrderByWithRelationInput
  children?: Prisma.SourceFolderOrderByRelationAggregateInput
  deck?: Prisma.DeckOrderByWithRelationInput
  sources?: Prisma.SourceOrderByRelationAggregateInput
}

export type SourceFolderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_name_parentId_deckId?: Prisma.SourceFolderUserIdNameParentIdDeckIdCompoundUniqueInput
  AND?: Prisma.SourceFolderWhereInput | Prisma.SourceFolderWhereInput[]
  OR?: Prisma.SourceFolderWhereInput[]
  NOT?: Prisma.SourceFolderWhereInput | Prisma.SourceFolderWhereInput[]
  userId?: Prisma.StringFilter<"SourceFolder"> | string
  name?: Prisma.StringFilter<"SourceFolder"> | string
  parentId?: Prisma.StringNullableFilter<"SourceFolder"> | string | null
  deckId?: Prisma.StringNullableFilter<"SourceFolder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SourceFolder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SourceFolder"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  parent?: Prisma.XOR<Prisma.SourceFolderNullableScalarRelationFilter, Prisma.SourceFolderWhereInput> | null
  children?: Prisma.SourceFolderListRelationFilter
  deck?: Prisma.XOR<Prisma.DeckNullableScalarRelationFilter, Prisma.DeckWhereInput> | null
  sources?: Prisma.SourceListRelationFilter
}, "id" | "userId_name_parentId_deckId">

export type SourceFolderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  deckId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SourceFolderCountOrderByAggregateInput
  _max?: Prisma.SourceFolderMaxOrderByAggregateInput
  _min?: Prisma.SourceFolderMinOrderByAggregateInput
}

export type SourceFolderScalarWhereWithAggregatesInput = {
  AND?: Prisma.SourceFolderScalarWhereWithAggregatesInput | Prisma.SourceFolderScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourceFolderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SourceFolderScalarWhereWithAggregatesInput | Prisma.SourceFolderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SourceFolder"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SourceFolder"> | string
  name?: Prisma.StringWithAggregatesFilter<"SourceFolder"> | string
  parentId?: Prisma.StringNullableWithAggregatesFilter<"SourceFolder"> | string | null
  deckId?: Prisma.StringNullableWithAggregatesFilter<"SourceFolder"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SourceFolder"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SourceFolder"> | Date | string
}

export type SourceFolderCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSourceFoldersInput
  parent?: Prisma.SourceFolderCreateNestedOneWithoutChildrenInput
  children?: Prisma.SourceFolderCreateNestedManyWithoutParentInput
  deck?: Prisma.DeckCreateNestedOneWithoutFoldersInput
  sources?: Prisma.SourceCreateNestedManyWithoutFolderInput
}

export type SourceFolderUncheckedCreateInput = {
  id?: string
  userId: string
  name: string
  parentId?: string | null
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.SourceFolderUncheckedCreateNestedManyWithoutParentInput
  sources?: Prisma.SourceUncheckedCreateNestedManyWithoutFolderInput
}

export type SourceFolderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSourceFoldersNestedInput
  parent?: Prisma.SourceFolderUpdateOneWithoutChildrenNestedInput
  children?: Prisma.SourceFolderUpdateManyWithoutParentNestedInput
  deck?: Prisma.DeckUpdateOneWithoutFoldersNestedInput
  sources?: Prisma.SourceUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.SourceFolderUncheckedUpdateManyWithoutParentNestedInput
  sources?: Prisma.SourceUncheckedUpdateManyWithoutFolderNestedInput
}

export type SourceFolderCreateManyInput = {
  id?: string
  userId: string
  name: string
  parentId?: string | null
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceFolderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceFolderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceFolderListRelationFilter = {
  every?: Prisma.SourceFolderWhereInput
  some?: Prisma.SourceFolderWhereInput
  none?: Prisma.SourceFolderWhereInput
}

export type SourceFolderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SourceFolderNullableScalarRelationFilter = {
  is?: Prisma.SourceFolderWhereInput | null
  isNot?: Prisma.SourceFolderWhereInput | null
}

export type SourceFolderUserIdNameParentIdDeckIdCompoundUniqueInput = {
  userId: string
  name: string
  parentId: string
  deckId: string
}

export type SourceFolderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  deckId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceFolderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  deckId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceFolderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  deckId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceFolderCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutUserInput, Prisma.SourceFolderUncheckedCreateWithoutUserInput> | Prisma.SourceFolderCreateWithoutUserInput[] | Prisma.SourceFolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutUserInput | Prisma.SourceFolderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SourceFolderCreateManyUserInputEnvelope
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
}

export type SourceFolderUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutUserInput, Prisma.SourceFolderUncheckedCreateWithoutUserInput> | Prisma.SourceFolderCreateWithoutUserInput[] | Prisma.SourceFolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutUserInput | Prisma.SourceFolderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SourceFolderCreateManyUserInputEnvelope
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
}

export type SourceFolderUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutUserInput, Prisma.SourceFolderUncheckedCreateWithoutUserInput> | Prisma.SourceFolderCreateWithoutUserInput[] | Prisma.SourceFolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutUserInput | Prisma.SourceFolderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SourceFolderUpsertWithWhereUniqueWithoutUserInput | Prisma.SourceFolderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SourceFolderCreateManyUserInputEnvelope
  set?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  disconnect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  delete?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  update?: Prisma.SourceFolderUpdateWithWhereUniqueWithoutUserInput | Prisma.SourceFolderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SourceFolderUpdateManyWithWhereWithoutUserInput | Prisma.SourceFolderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
}

export type SourceFolderUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutUserInput, Prisma.SourceFolderUncheckedCreateWithoutUserInput> | Prisma.SourceFolderCreateWithoutUserInput[] | Prisma.SourceFolderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutUserInput | Prisma.SourceFolderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SourceFolderUpsertWithWhereUniqueWithoutUserInput | Prisma.SourceFolderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SourceFolderCreateManyUserInputEnvelope
  set?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  disconnect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  delete?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  update?: Prisma.SourceFolderUpdateWithWhereUniqueWithoutUserInput | Prisma.SourceFolderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SourceFolderUpdateManyWithWhereWithoutUserInput | Prisma.SourceFolderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
}

export type SourceFolderCreateNestedManyWithoutDeckInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutDeckInput, Prisma.SourceFolderUncheckedCreateWithoutDeckInput> | Prisma.SourceFolderCreateWithoutDeckInput[] | Prisma.SourceFolderUncheckedCreateWithoutDeckInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutDeckInput | Prisma.SourceFolderCreateOrConnectWithoutDeckInput[]
  createMany?: Prisma.SourceFolderCreateManyDeckInputEnvelope
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
}

export type SourceFolderUncheckedCreateNestedManyWithoutDeckInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutDeckInput, Prisma.SourceFolderUncheckedCreateWithoutDeckInput> | Prisma.SourceFolderCreateWithoutDeckInput[] | Prisma.SourceFolderUncheckedCreateWithoutDeckInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutDeckInput | Prisma.SourceFolderCreateOrConnectWithoutDeckInput[]
  createMany?: Prisma.SourceFolderCreateManyDeckInputEnvelope
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
}

export type SourceFolderUpdateManyWithoutDeckNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutDeckInput, Prisma.SourceFolderUncheckedCreateWithoutDeckInput> | Prisma.SourceFolderCreateWithoutDeckInput[] | Prisma.SourceFolderUncheckedCreateWithoutDeckInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutDeckInput | Prisma.SourceFolderCreateOrConnectWithoutDeckInput[]
  upsert?: Prisma.SourceFolderUpsertWithWhereUniqueWithoutDeckInput | Prisma.SourceFolderUpsertWithWhereUniqueWithoutDeckInput[]
  createMany?: Prisma.SourceFolderCreateManyDeckInputEnvelope
  set?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  disconnect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  delete?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  update?: Prisma.SourceFolderUpdateWithWhereUniqueWithoutDeckInput | Prisma.SourceFolderUpdateWithWhereUniqueWithoutDeckInput[]
  updateMany?: Prisma.SourceFolderUpdateManyWithWhereWithoutDeckInput | Prisma.SourceFolderUpdateManyWithWhereWithoutDeckInput[]
  deleteMany?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
}

export type SourceFolderUncheckedUpdateManyWithoutDeckNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutDeckInput, Prisma.SourceFolderUncheckedCreateWithoutDeckInput> | Prisma.SourceFolderCreateWithoutDeckInput[] | Prisma.SourceFolderUncheckedCreateWithoutDeckInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutDeckInput | Prisma.SourceFolderCreateOrConnectWithoutDeckInput[]
  upsert?: Prisma.SourceFolderUpsertWithWhereUniqueWithoutDeckInput | Prisma.SourceFolderUpsertWithWhereUniqueWithoutDeckInput[]
  createMany?: Prisma.SourceFolderCreateManyDeckInputEnvelope
  set?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  disconnect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  delete?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  update?: Prisma.SourceFolderUpdateWithWhereUniqueWithoutDeckInput | Prisma.SourceFolderUpdateWithWhereUniqueWithoutDeckInput[]
  updateMany?: Prisma.SourceFolderUpdateManyWithWhereWithoutDeckInput | Prisma.SourceFolderUpdateManyWithWhereWithoutDeckInput[]
  deleteMany?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
}

export type SourceFolderCreateNestedOneWithoutSourcesInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutSourcesInput, Prisma.SourceFolderUncheckedCreateWithoutSourcesInput>
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutSourcesInput
  connect?: Prisma.SourceFolderWhereUniqueInput
}

export type SourceFolderUpdateOneWithoutSourcesNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutSourcesInput, Prisma.SourceFolderUncheckedCreateWithoutSourcesInput>
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutSourcesInput
  upsert?: Prisma.SourceFolderUpsertWithoutSourcesInput
  disconnect?: Prisma.SourceFolderWhereInput | boolean
  delete?: Prisma.SourceFolderWhereInput | boolean
  connect?: Prisma.SourceFolderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SourceFolderUpdateToOneWithWhereWithoutSourcesInput, Prisma.SourceFolderUpdateWithoutSourcesInput>, Prisma.SourceFolderUncheckedUpdateWithoutSourcesInput>
}

export type SourceFolderCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutChildrenInput, Prisma.SourceFolderUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutChildrenInput
  connect?: Prisma.SourceFolderWhereUniqueInput
}

export type SourceFolderCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutParentInput, Prisma.SourceFolderUncheckedCreateWithoutParentInput> | Prisma.SourceFolderCreateWithoutParentInput[] | Prisma.SourceFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutParentInput | Prisma.SourceFolderCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.SourceFolderCreateManyParentInputEnvelope
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
}

export type SourceFolderUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutParentInput, Prisma.SourceFolderUncheckedCreateWithoutParentInput> | Prisma.SourceFolderCreateWithoutParentInput[] | Prisma.SourceFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutParentInput | Prisma.SourceFolderCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.SourceFolderCreateManyParentInputEnvelope
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
}

export type SourceFolderUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutChildrenInput, Prisma.SourceFolderUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.SourceFolderUpsertWithoutChildrenInput
  disconnect?: Prisma.SourceFolderWhereInput | boolean
  delete?: Prisma.SourceFolderWhereInput | boolean
  connect?: Prisma.SourceFolderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SourceFolderUpdateToOneWithWhereWithoutChildrenInput, Prisma.SourceFolderUpdateWithoutChildrenInput>, Prisma.SourceFolderUncheckedUpdateWithoutChildrenInput>
}

export type SourceFolderUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutParentInput, Prisma.SourceFolderUncheckedCreateWithoutParentInput> | Prisma.SourceFolderCreateWithoutParentInput[] | Prisma.SourceFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutParentInput | Prisma.SourceFolderCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.SourceFolderUpsertWithWhereUniqueWithoutParentInput | Prisma.SourceFolderUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.SourceFolderCreateManyParentInputEnvelope
  set?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  disconnect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  delete?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  update?: Prisma.SourceFolderUpdateWithWhereUniqueWithoutParentInput | Prisma.SourceFolderUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.SourceFolderUpdateManyWithWhereWithoutParentInput | Prisma.SourceFolderUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
}

export type SourceFolderUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.SourceFolderCreateWithoutParentInput, Prisma.SourceFolderUncheckedCreateWithoutParentInput> | Prisma.SourceFolderCreateWithoutParentInput[] | Prisma.SourceFolderUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.SourceFolderCreateOrConnectWithoutParentInput | Prisma.SourceFolderCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.SourceFolderUpsertWithWhereUniqueWithoutParentInput | Prisma.SourceFolderUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.SourceFolderCreateManyParentInputEnvelope
  set?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  disconnect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  delete?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  connect?: Prisma.SourceFolderWhereUniqueInput | Prisma.SourceFolderWhereUniqueInput[]
  update?: Prisma.SourceFolderUpdateWithWhereUniqueWithoutParentInput | Prisma.SourceFolderUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.SourceFolderUpdateManyWithWhereWithoutParentInput | Prisma.SourceFolderUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
}

export type SourceFolderCreateWithoutUserInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.SourceFolderCreateNestedOneWithoutChildrenInput
  children?: Prisma.SourceFolderCreateNestedManyWithoutParentInput
  deck?: Prisma.DeckCreateNestedOneWithoutFoldersInput
  sources?: Prisma.SourceCreateNestedManyWithoutFolderInput
}

export type SourceFolderUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  parentId?: string | null
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.SourceFolderUncheckedCreateNestedManyWithoutParentInput
  sources?: Prisma.SourceUncheckedCreateNestedManyWithoutFolderInput
}

export type SourceFolderCreateOrConnectWithoutUserInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutUserInput, Prisma.SourceFolderUncheckedCreateWithoutUserInput>
}

export type SourceFolderCreateManyUserInputEnvelope = {
  data: Prisma.SourceFolderCreateManyUserInput | Prisma.SourceFolderCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SourceFolderUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  update: Prisma.XOR<Prisma.SourceFolderUpdateWithoutUserInput, Prisma.SourceFolderUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutUserInput, Prisma.SourceFolderUncheckedCreateWithoutUserInput>
}

export type SourceFolderUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateWithoutUserInput, Prisma.SourceFolderUncheckedUpdateWithoutUserInput>
}

export type SourceFolderUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SourceFolderScalarWhereInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateManyMutationInput, Prisma.SourceFolderUncheckedUpdateManyWithoutUserInput>
}

export type SourceFolderScalarWhereInput = {
  AND?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
  OR?: Prisma.SourceFolderScalarWhereInput[]
  NOT?: Prisma.SourceFolderScalarWhereInput | Prisma.SourceFolderScalarWhereInput[]
  id?: Prisma.StringFilter<"SourceFolder"> | string
  userId?: Prisma.StringFilter<"SourceFolder"> | string
  name?: Prisma.StringFilter<"SourceFolder"> | string
  parentId?: Prisma.StringNullableFilter<"SourceFolder"> | string | null
  deckId?: Prisma.StringNullableFilter<"SourceFolder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SourceFolder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SourceFolder"> | Date | string
}

export type SourceFolderCreateWithoutDeckInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSourceFoldersInput
  parent?: Prisma.SourceFolderCreateNestedOneWithoutChildrenInput
  children?: Prisma.SourceFolderCreateNestedManyWithoutParentInput
  sources?: Prisma.SourceCreateNestedManyWithoutFolderInput
}

export type SourceFolderUncheckedCreateWithoutDeckInput = {
  id?: string
  userId: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.SourceFolderUncheckedCreateNestedManyWithoutParentInput
  sources?: Prisma.SourceUncheckedCreateNestedManyWithoutFolderInput
}

export type SourceFolderCreateOrConnectWithoutDeckInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutDeckInput, Prisma.SourceFolderUncheckedCreateWithoutDeckInput>
}

export type SourceFolderCreateManyDeckInputEnvelope = {
  data: Prisma.SourceFolderCreateManyDeckInput | Prisma.SourceFolderCreateManyDeckInput[]
  skipDuplicates?: boolean
}

export type SourceFolderUpsertWithWhereUniqueWithoutDeckInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  update: Prisma.XOR<Prisma.SourceFolderUpdateWithoutDeckInput, Prisma.SourceFolderUncheckedUpdateWithoutDeckInput>
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutDeckInput, Prisma.SourceFolderUncheckedCreateWithoutDeckInput>
}

export type SourceFolderUpdateWithWhereUniqueWithoutDeckInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateWithoutDeckInput, Prisma.SourceFolderUncheckedUpdateWithoutDeckInput>
}

export type SourceFolderUpdateManyWithWhereWithoutDeckInput = {
  where: Prisma.SourceFolderScalarWhereInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateManyMutationInput, Prisma.SourceFolderUncheckedUpdateManyWithoutDeckInput>
}

export type SourceFolderCreateWithoutSourcesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSourceFoldersInput
  parent?: Prisma.SourceFolderCreateNestedOneWithoutChildrenInput
  children?: Prisma.SourceFolderCreateNestedManyWithoutParentInput
  deck?: Prisma.DeckCreateNestedOneWithoutFoldersInput
}

export type SourceFolderUncheckedCreateWithoutSourcesInput = {
  id?: string
  userId: string
  name: string
  parentId?: string | null
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.SourceFolderUncheckedCreateNestedManyWithoutParentInput
}

export type SourceFolderCreateOrConnectWithoutSourcesInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutSourcesInput, Prisma.SourceFolderUncheckedCreateWithoutSourcesInput>
}

export type SourceFolderUpsertWithoutSourcesInput = {
  update: Prisma.XOR<Prisma.SourceFolderUpdateWithoutSourcesInput, Prisma.SourceFolderUncheckedUpdateWithoutSourcesInput>
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutSourcesInput, Prisma.SourceFolderUncheckedCreateWithoutSourcesInput>
  where?: Prisma.SourceFolderWhereInput
}

export type SourceFolderUpdateToOneWithWhereWithoutSourcesInput = {
  where?: Prisma.SourceFolderWhereInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateWithoutSourcesInput, Prisma.SourceFolderUncheckedUpdateWithoutSourcesInput>
}

export type SourceFolderUpdateWithoutSourcesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSourceFoldersNestedInput
  parent?: Prisma.SourceFolderUpdateOneWithoutChildrenNestedInput
  children?: Prisma.SourceFolderUpdateManyWithoutParentNestedInput
  deck?: Prisma.DeckUpdateOneWithoutFoldersNestedInput
}

export type SourceFolderUncheckedUpdateWithoutSourcesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.SourceFolderUncheckedUpdateManyWithoutParentNestedInput
}

export type SourceFolderCreateWithoutChildrenInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSourceFoldersInput
  parent?: Prisma.SourceFolderCreateNestedOneWithoutChildrenInput
  deck?: Prisma.DeckCreateNestedOneWithoutFoldersInput
  sources?: Prisma.SourceCreateNestedManyWithoutFolderInput
}

export type SourceFolderUncheckedCreateWithoutChildrenInput = {
  id?: string
  userId: string
  name: string
  parentId?: string | null
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.SourceUncheckedCreateNestedManyWithoutFolderInput
}

export type SourceFolderCreateOrConnectWithoutChildrenInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutChildrenInput, Prisma.SourceFolderUncheckedCreateWithoutChildrenInput>
}

export type SourceFolderCreateWithoutParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSourceFoldersInput
  children?: Prisma.SourceFolderCreateNestedManyWithoutParentInput
  deck?: Prisma.DeckCreateNestedOneWithoutFoldersInput
  sources?: Prisma.SourceCreateNestedManyWithoutFolderInput
}

export type SourceFolderUncheckedCreateWithoutParentInput = {
  id?: string
  userId: string
  name: string
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.SourceFolderUncheckedCreateNestedManyWithoutParentInput
  sources?: Prisma.SourceUncheckedCreateNestedManyWithoutFolderInput
}

export type SourceFolderCreateOrConnectWithoutParentInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutParentInput, Prisma.SourceFolderUncheckedCreateWithoutParentInput>
}

export type SourceFolderCreateManyParentInputEnvelope = {
  data: Prisma.SourceFolderCreateManyParentInput | Prisma.SourceFolderCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type SourceFolderUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.SourceFolderUpdateWithoutChildrenInput, Prisma.SourceFolderUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutChildrenInput, Prisma.SourceFolderUncheckedCreateWithoutChildrenInput>
  where?: Prisma.SourceFolderWhereInput
}

export type SourceFolderUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.SourceFolderWhereInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateWithoutChildrenInput, Prisma.SourceFolderUncheckedUpdateWithoutChildrenInput>
}

export type SourceFolderUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSourceFoldersNestedInput
  parent?: Prisma.SourceFolderUpdateOneWithoutChildrenNestedInput
  deck?: Prisma.DeckUpdateOneWithoutFoldersNestedInput
  sources?: Prisma.SourceUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.SourceUncheckedUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  update: Prisma.XOR<Prisma.SourceFolderUpdateWithoutParentInput, Prisma.SourceFolderUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.SourceFolderCreateWithoutParentInput, Prisma.SourceFolderUncheckedCreateWithoutParentInput>
}

export type SourceFolderUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.SourceFolderWhereUniqueInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateWithoutParentInput, Prisma.SourceFolderUncheckedUpdateWithoutParentInput>
}

export type SourceFolderUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.SourceFolderScalarWhereInput
  data: Prisma.XOR<Prisma.SourceFolderUpdateManyMutationInput, Prisma.SourceFolderUncheckedUpdateManyWithoutParentInput>
}

export type SourceFolderCreateManyUserInput = {
  id?: string
  name: string
  parentId?: string | null
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceFolderUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.SourceFolderUpdateOneWithoutChildrenNestedInput
  children?: Prisma.SourceFolderUpdateManyWithoutParentNestedInput
  deck?: Prisma.DeckUpdateOneWithoutFoldersNestedInput
  sources?: Prisma.SourceUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.SourceFolderUncheckedUpdateManyWithoutParentNestedInput
  sources?: Prisma.SourceUncheckedUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceFolderCreateManyDeckInput = {
  id?: string
  userId: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceFolderUpdateWithoutDeckInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSourceFoldersNestedInput
  parent?: Prisma.SourceFolderUpdateOneWithoutChildrenNestedInput
  children?: Prisma.SourceFolderUpdateManyWithoutParentNestedInput
  sources?: Prisma.SourceUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateWithoutDeckInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.SourceFolderUncheckedUpdateManyWithoutParentNestedInput
  sources?: Prisma.SourceUncheckedUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateManyWithoutDeckInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceFolderCreateManyParentInput = {
  id?: string
  userId: string
  name: string
  deckId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceFolderUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSourceFoldersNestedInput
  children?: Prisma.SourceFolderUpdateManyWithoutParentNestedInput
  deck?: Prisma.DeckUpdateOneWithoutFoldersNestedInput
  sources?: Prisma.SourceUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.SourceFolderUncheckedUpdateManyWithoutParentNestedInput
  sources?: Prisma.SourceUncheckedUpdateManyWithoutFolderNestedInput
}

export type SourceFolderUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deckId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SourceFolderCountOutputType
 */

export type SourceFolderCountOutputType = {
  children: number
  sources: number
}

export type SourceFolderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  children?: boolean | SourceFolderCountOutputTypeCountChildrenArgs
  sources?: boolean | SourceFolderCountOutputTypeCountSourcesArgs
}

/**
 * SourceFolderCountOutputType without action
 */
export type SourceFolderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolderCountOutputType
   */
  select?: Prisma.SourceFolderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SourceFolderCountOutputType without action
 */
export type SourceFolderCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceFolderWhereInput
}

/**
 * SourceFolderCountOutputType without action
 */
export type SourceFolderCountOutputTypeCountSourcesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceWhereInput
}


export type SourceFolderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  parentId?: boolean
  deckId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.SourceFolder$parentArgs<ExtArgs>
  children?: boolean | Prisma.SourceFolder$childrenArgs<ExtArgs>
  deck?: boolean | Prisma.SourceFolder$deckArgs<ExtArgs>
  sources?: boolean | Prisma.SourceFolder$sourcesArgs<ExtArgs>
  _count?: boolean | Prisma.SourceFolderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sourceFolder"]>

export type SourceFolderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  parentId?: boolean
  deckId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.SourceFolder$parentArgs<ExtArgs>
  deck?: boolean | Prisma.SourceFolder$deckArgs<ExtArgs>
}, ExtArgs["result"]["sourceFolder"]>

export type SourceFolderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  parentId?: boolean
  deckId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.SourceFolder$parentArgs<ExtArgs>
  deck?: boolean | Prisma.SourceFolder$deckArgs<ExtArgs>
}, ExtArgs["result"]["sourceFolder"]>

export type SourceFolderSelectScalar = {
  id?: boolean
  userId?: boolean
  name?: boolean
  parentId?: boolean
  deckId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SourceFolderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "name" | "parentId" | "deckId" | "createdAt" | "updatedAt", ExtArgs["result"]["sourceFolder"]>
export type SourceFolderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.SourceFolder$parentArgs<ExtArgs>
  children?: boolean | Prisma.SourceFolder$childrenArgs<ExtArgs>
  deck?: boolean | Prisma.SourceFolder$deckArgs<ExtArgs>
  sources?: boolean | Prisma.SourceFolder$sourcesArgs<ExtArgs>
  _count?: boolean | Prisma.SourceFolderCountOutputTypeDefaultArgs<ExtArgs>
}
export type SourceFolderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.SourceFolder$parentArgs<ExtArgs>
  deck?: boolean | Prisma.SourceFolder$deckArgs<ExtArgs>
}
export type SourceFolderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  parent?: boolean | Prisma.SourceFolder$parentArgs<ExtArgs>
  deck?: boolean | Prisma.SourceFolder$deckArgs<ExtArgs>
}

export type $SourceFolderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SourceFolder"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    parent: Prisma.$SourceFolderPayload<ExtArgs> | null
    children: Prisma.$SourceFolderPayload<ExtArgs>[]
    deck: Prisma.$DeckPayload<ExtArgs> | null
    sources: Prisma.$SourcePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    name: string
    parentId: string | null
    deckId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sourceFolder"]>
  composites: {}
}

export type SourceFolderGetPayload<S extends boolean | null | undefined | SourceFolderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload, S>

export type SourceFolderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SourceFolderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SourceFolderCountAggregateInputType | true
  }

export interface SourceFolderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SourceFolder'], meta: { name: 'SourceFolder' } }
  /**
   * Find zero or one SourceFolder that matches the filter.
   * @param {SourceFolderFindUniqueArgs} args - Arguments to find a SourceFolder
   * @example
   * // Get one SourceFolder
   * const sourceFolder = await prisma.sourceFolder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourceFolderFindUniqueArgs>(args: Prisma.SelectSubset<T, SourceFolderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SourceFolder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourceFolderFindUniqueOrThrowArgs} args - Arguments to find a SourceFolder
   * @example
   * // Get one SourceFolder
   * const sourceFolder = await prisma.sourceFolder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourceFolderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SourceFolderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceFolder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderFindFirstArgs} args - Arguments to find a SourceFolder
   * @example
   * // Get one SourceFolder
   * const sourceFolder = await prisma.sourceFolder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourceFolderFindFirstArgs>(args?: Prisma.SelectSubset<T, SourceFolderFindFirstArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceFolder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderFindFirstOrThrowArgs} args - Arguments to find a SourceFolder
   * @example
   * // Get one SourceFolder
   * const sourceFolder = await prisma.sourceFolder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourceFolderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SourceFolderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SourceFolders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SourceFolders
   * const sourceFolders = await prisma.sourceFolder.findMany()
   * 
   * // Get first 10 SourceFolders
   * const sourceFolders = await prisma.sourceFolder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sourceFolderWithIdOnly = await prisma.sourceFolder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SourceFolderFindManyArgs>(args?: Prisma.SelectSubset<T, SourceFolderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SourceFolder.
   * @param {SourceFolderCreateArgs} args - Arguments to create a SourceFolder.
   * @example
   * // Create one SourceFolder
   * const SourceFolder = await prisma.sourceFolder.create({
   *   data: {
   *     // ... data to create a SourceFolder
   *   }
   * })
   * 
   */
  create<T extends SourceFolderCreateArgs>(args: Prisma.SelectSubset<T, SourceFolderCreateArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SourceFolders.
   * @param {SourceFolderCreateManyArgs} args - Arguments to create many SourceFolders.
   * @example
   * // Create many SourceFolders
   * const sourceFolder = await prisma.sourceFolder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SourceFolderCreateManyArgs>(args?: Prisma.SelectSubset<T, SourceFolderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SourceFolders and returns the data saved in the database.
   * @param {SourceFolderCreateManyAndReturnArgs} args - Arguments to create many SourceFolders.
   * @example
   * // Create many SourceFolders
   * const sourceFolder = await prisma.sourceFolder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SourceFolders and only return the `id`
   * const sourceFolderWithIdOnly = await prisma.sourceFolder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SourceFolderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SourceFolderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SourceFolder.
   * @param {SourceFolderDeleteArgs} args - Arguments to delete one SourceFolder.
   * @example
   * // Delete one SourceFolder
   * const SourceFolder = await prisma.sourceFolder.delete({
   *   where: {
   *     // ... filter to delete one SourceFolder
   *   }
   * })
   * 
   */
  delete<T extends SourceFolderDeleteArgs>(args: Prisma.SelectSubset<T, SourceFolderDeleteArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SourceFolder.
   * @param {SourceFolderUpdateArgs} args - Arguments to update one SourceFolder.
   * @example
   * // Update one SourceFolder
   * const sourceFolder = await prisma.sourceFolder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SourceFolderUpdateArgs>(args: Prisma.SelectSubset<T, SourceFolderUpdateArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SourceFolders.
   * @param {SourceFolderDeleteManyArgs} args - Arguments to filter SourceFolders to delete.
   * @example
   * // Delete a few SourceFolders
   * const { count } = await prisma.sourceFolder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SourceFolderDeleteManyArgs>(args?: Prisma.SelectSubset<T, SourceFolderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceFolders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SourceFolders
   * const sourceFolder = await prisma.sourceFolder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SourceFolderUpdateManyArgs>(args: Prisma.SelectSubset<T, SourceFolderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceFolders and returns the data updated in the database.
   * @param {SourceFolderUpdateManyAndReturnArgs} args - Arguments to update many SourceFolders.
   * @example
   * // Update many SourceFolders
   * const sourceFolder = await prisma.sourceFolder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SourceFolders and only return the `id`
   * const sourceFolderWithIdOnly = await prisma.sourceFolder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SourceFolderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SourceFolderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SourceFolder.
   * @param {SourceFolderUpsertArgs} args - Arguments to update or create a SourceFolder.
   * @example
   * // Update or create a SourceFolder
   * const sourceFolder = await prisma.sourceFolder.upsert({
   *   create: {
   *     // ... data to create a SourceFolder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SourceFolder we want to update
   *   }
   * })
   */
  upsert<T extends SourceFolderUpsertArgs>(args: Prisma.SelectSubset<T, SourceFolderUpsertArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SourceFolders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderCountArgs} args - Arguments to filter SourceFolders to count.
   * @example
   * // Count the number of SourceFolders
   * const count = await prisma.sourceFolder.count({
   *   where: {
   *     // ... the filter for the SourceFolders we want to count
   *   }
   * })
  **/
  count<T extends SourceFolderCountArgs>(
    args?: Prisma.Subset<T, SourceFolderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceFolderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SourceFolder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourceFolderAggregateArgs>(args: Prisma.Subset<T, SourceFolderAggregateArgs>): Prisma.PrismaPromise<GetSourceFolderAggregateType<T>>

  /**
   * Group by SourceFolder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceFolderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SourceFolderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourceFolderGroupByArgs['orderBy'] }
      : { orderBy?: SourceFolderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SourceFolderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourceFolderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SourceFolder model
 */
readonly fields: SourceFolderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SourceFolder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourceFolderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  parent<T extends Prisma.SourceFolder$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SourceFolder$parentArgs<ExtArgs>>): Prisma.Prisma__SourceFolderClient<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.SourceFolder$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SourceFolder$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceFolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  deck<T extends Prisma.SourceFolder$deckArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SourceFolder$deckArgs<ExtArgs>>): Prisma.Prisma__DeckClient<runtime.Types.Result.GetResult<Prisma.$DeckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  sources<T extends Prisma.SourceFolder$sourcesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SourceFolder$sourcesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourcePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SourceFolder model
 */
export interface SourceFolderFieldRefs {
  readonly id: Prisma.FieldRef<"SourceFolder", 'String'>
  readonly userId: Prisma.FieldRef<"SourceFolder", 'String'>
  readonly name: Prisma.FieldRef<"SourceFolder", 'String'>
  readonly parentId: Prisma.FieldRef<"SourceFolder", 'String'>
  readonly deckId: Prisma.FieldRef<"SourceFolder", 'String'>
  readonly createdAt: Prisma.FieldRef<"SourceFolder", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SourceFolder", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SourceFolder findUnique
 */
export type SourceFolderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * Filter, which SourceFolder to fetch.
   */
  where: Prisma.SourceFolderWhereUniqueInput
}

/**
 * SourceFolder findUniqueOrThrow
 */
export type SourceFolderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * Filter, which SourceFolder to fetch.
   */
  where: Prisma.SourceFolderWhereUniqueInput
}

/**
 * SourceFolder findFirst
 */
export type SourceFolderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * Filter, which SourceFolder to fetch.
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceFolders to fetch.
   */
  orderBy?: Prisma.SourceFolderOrderByWithRelationInput | Prisma.SourceFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceFolders.
   */
  cursor?: Prisma.SourceFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceFolders.
   */
  distinct?: Prisma.SourceFolderScalarFieldEnum | Prisma.SourceFolderScalarFieldEnum[]
}

/**
 * SourceFolder findFirstOrThrow
 */
export type SourceFolderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * Filter, which SourceFolder to fetch.
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceFolders to fetch.
   */
  orderBy?: Prisma.SourceFolderOrderByWithRelationInput | Prisma.SourceFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceFolders.
   */
  cursor?: Prisma.SourceFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceFolders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceFolders.
   */
  distinct?: Prisma.SourceFolderScalarFieldEnum | Prisma.SourceFolderScalarFieldEnum[]
}

/**
 * SourceFolder findMany
 */
export type SourceFolderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * Filter, which SourceFolders to fetch.
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceFolders to fetch.
   */
  orderBy?: Prisma.SourceFolderOrderByWithRelationInput | Prisma.SourceFolderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SourceFolders.
   */
  cursor?: Prisma.SourceFolderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceFolders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceFolders.
   */
  skip?: number
  distinct?: Prisma.SourceFolderScalarFieldEnum | Prisma.SourceFolderScalarFieldEnum[]
}

/**
 * SourceFolder create
 */
export type SourceFolderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * The data needed to create a SourceFolder.
   */
  data: Prisma.XOR<Prisma.SourceFolderCreateInput, Prisma.SourceFolderUncheckedCreateInput>
}

/**
 * SourceFolder createMany
 */
export type SourceFolderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SourceFolders.
   */
  data: Prisma.SourceFolderCreateManyInput | Prisma.SourceFolderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SourceFolder createManyAndReturn
 */
export type SourceFolderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * The data used to create many SourceFolders.
   */
  data: Prisma.SourceFolderCreateManyInput | Prisma.SourceFolderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SourceFolder update
 */
export type SourceFolderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * The data needed to update a SourceFolder.
   */
  data: Prisma.XOR<Prisma.SourceFolderUpdateInput, Prisma.SourceFolderUncheckedUpdateInput>
  /**
   * Choose, which SourceFolder to update.
   */
  where: Prisma.SourceFolderWhereUniqueInput
}

/**
 * SourceFolder updateMany
 */
export type SourceFolderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SourceFolders.
   */
  data: Prisma.XOR<Prisma.SourceFolderUpdateManyMutationInput, Prisma.SourceFolderUncheckedUpdateManyInput>
  /**
   * Filter which SourceFolders to update
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * Limit how many SourceFolders to update.
   */
  limit?: number
}

/**
 * SourceFolder updateManyAndReturn
 */
export type SourceFolderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * The data used to update SourceFolders.
   */
  data: Prisma.XOR<Prisma.SourceFolderUpdateManyMutationInput, Prisma.SourceFolderUncheckedUpdateManyInput>
  /**
   * Filter which SourceFolders to update
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * Limit how many SourceFolders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SourceFolder upsert
 */
export type SourceFolderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * The filter to search for the SourceFolder to update in case it exists.
   */
  where: Prisma.SourceFolderWhereUniqueInput
  /**
   * In case the SourceFolder found by the `where` argument doesn't exist, create a new SourceFolder with this data.
   */
  create: Prisma.XOR<Prisma.SourceFolderCreateInput, Prisma.SourceFolderUncheckedCreateInput>
  /**
   * In case the SourceFolder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourceFolderUpdateInput, Prisma.SourceFolderUncheckedUpdateInput>
}

/**
 * SourceFolder delete
 */
export type SourceFolderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  /**
   * Filter which SourceFolder to delete.
   */
  where: Prisma.SourceFolderWhereUniqueInput
}

/**
 * SourceFolder deleteMany
 */
export type SourceFolderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceFolders to delete
   */
  where?: Prisma.SourceFolderWhereInput
  /**
   * Limit how many SourceFolders to delete.
   */
  limit?: number
}

/**
 * SourceFolder.parent
 */
export type SourceFolder$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  where?: Prisma.SourceFolderWhereInput
}

/**
 * SourceFolder.children
 */
export type SourceFolder$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
  where?: Prisma.SourceFolderWhereInput
  orderBy?: Prisma.SourceFolderOrderByWithRelationInput | Prisma.SourceFolderOrderByWithRelationInput[]
  cursor?: Prisma.SourceFolderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SourceFolderScalarFieldEnum | Prisma.SourceFolderScalarFieldEnum[]
}

/**
 * SourceFolder.deck
 */
export type SourceFolder$deckArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deck
   */
  select?: Prisma.DeckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deck
   */
  omit?: Prisma.DeckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeckInclude<ExtArgs> | null
  where?: Prisma.DeckWhereInput
}

/**
 * SourceFolder.sources
 */
export type SourceFolder$sourcesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Source
   */
  select?: Prisma.SourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Source
   */
  omit?: Prisma.SourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceInclude<ExtArgs> | null
  where?: Prisma.SourceWhereInput
  orderBy?: Prisma.SourceOrderByWithRelationInput | Prisma.SourceOrderByWithRelationInput[]
  cursor?: Prisma.SourceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SourceScalarFieldEnum | Prisma.SourceScalarFieldEnum[]
}

/**
 * SourceFolder without action
 */
export type SourceFolderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceFolder
   */
  select?: Prisma.SourceFolderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceFolder
   */
  omit?: Prisma.SourceFolderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceFolderInclude<ExtArgs> | null
}
